# go get -u -v github.com/go-task/task/cmd/task

version : 2

vars :
  main_module : src/Main.hs
  target      : jsonfmt
  tests       : tests/Main.hs
  deps_dir    : deps
  bin_dir     : ~/.local/bin
  build_dir   : build
  ghc         : /usr/bin/ghc

  modules :
    ./src/Json.hs
    ./src/Json/Parse.hs
    ./src/Json/Pretty.hs
    ./src/Parse.hs

  deps :
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Basics.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Char.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Dict.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/List.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Maybe.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Result.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Set.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/String.hs
    ./{{.deps_dir}}/aramiscd/ulme/src/Ulme/Tuple.hs
    ./{{.deps_dir}}/aramiscd/ulme-io/src/Ulme/IO.hs

  ghc_args :
    -hidir {{.build_dir}}
    -odir {{.build_dir}}
    -Werror
    -Weverything
    -Wno-missing-import-lists
    -Wno-missing-local-signatures
    -Wno-monomorphism-restriction
    -Wno-redundant-constraints
    -Wno-safe
    -Wno-type-defaults
    -XLambdaCase
    -XNoImplicitPrelude
    -XOverloadedStrings
    -XPackageImports
    -XStrict

  ghc_dev_args :
    -O0
    -Wno-missing-exported-signatures
    -Wno-missing-export-lists
    -Wno-missing-signatures
    -Wno-unsafe
    -Wno-unused-imports
    -Wno-unused-local-binds
    -Wno-unused-matches
    -Wno-unused-top-binds

  ghc_test_args : -Wno-unsafe

tasks :
  setup :
    cmds :
      [ " if [ ! -d {{.deps_dir}}/aramiscd/ulme ]
        ; then git clone git@eee.ygg:ulme {{.deps_dir}}/aramiscd/ulme
        ; fi
        "
      , " if [ ! -d {{.deps_dir}}/aramiscd/ulme-io ]
        ; then git clone git@eee.ygg:ulme-io {{.deps_dir}}/aramiscd/ulme-io
        ; fi
        "
      ]
    
  build :
    cmds :
      [ " mkdir -p {{.build_dir}} "
      , " {{.ghc}} {{.ghc_args}} {{.main_module}} {{.modules}} {{.deps}} -o {{.build_dir}}/{{.target}} "
      ]

  build-dev :
    cmds :
      [ " mkdir -p {{.build_dir}} "
      , " {{.ghc}} {{.ghc_args}} {{.ghc_dev_args}} {{.main_module}} {{.modules}} {{.deps}} -o {{.build_dir}}/{{.target}} "
      ]

  watch :
    silent : true
    cmds :
      [ " while true ; do inotifywait -e modify -q -r src ; task build-dev && clear && task run ; done " ]

  test :
    cmds :
      [ " mkdir -p {{.build_dir}} "
      , " {{.ghc}} {{.ghc_args}} {{.ghc_test_args}} {{.tests}} {{.modules}} {{.deps}} -o {{.build_dir}}/tests "
      , " {{.build_dir}}/tests "
      ]

  test-dev :
    cmds :
      [ " mkdir -p {{.build_dir}} "
      , " {{.ghc}} {{.ghc_args}} {{.ghc_dev_args}} {{.ghc_test_args}} {{.tests}} {{.modules}} {{.deps}} -o {{.build_dir}}/tests "
      , " {{.build_dir}}/tests "
      ]

  run :
    silent : true
    cmds :
      [ " echo
            ' {\"foo\":\"bla\",\"fooo\":\"bla\",\"foooo\":\"bla\"
              ,\"fooooo\":\"bla\",\"foo\":\"bla\",\"foo\":\"bla\"
              ,\"foo\":\"bla\",\"foo\":\"bla\"
              }
            '
        | {{.build_dir}}/{{.target}}
        "
      ]

  install :
    cmds : [ " cp {{.build_dir}}/{{.target}} {{.bin_dir}} " ]

  clean :
    cmds : [ " rm -rf {{.build_dir}} " ]

  clean-all :
      cmds : [ " rm -rf {{.build_dir}} {{.deps_dir}} " ]
